### ISSUE TITLE
Add symbolic constants for the signals

### ISSUE THREAD

**Issue by Yamakaky** [alexcrichton/tokio-signal#1]
Like `const SIGINT = 2`

**Comment by kamalmarhubi** [comment]
This should come from either libc or nix to ensure correctness.

**Comment by kamalmarhubi** [comment]
:-)

**Comment by Yamakaky** [comment]
Well, in fact it does https://doc.rust-lang.org/libc/x86_64-unknown-linux-gnu/libc/constant.SIGINT.html Maybe re-exporting, then?

**Comment by alexcrichton** [comment]
Sounds good to me!
