### ISSUE TITLE
SA_RESTART?

### ISSUE THREAD

**Issue by Rufflewind** [alexcrichton/tokio-signal#14]
What is the rationale for having `SA_RESTART` in the signal handler?  If I understood the docs correctly, the flag causes certain system calls to be automatically restart when the signal is received.  Doesn't this defeat the purpose of having signals - presumably you want it to interrupt whatever it was doing?

Edit: Testing shows that it does have an effect on blocking calls, but no effect on nonblocking calls (of course), so it shouldn't affect *normal* usage of Tokio where everything is nonblocking.  Still, I'm not sure why this flag is necessary?

**Comment by alexcrichton** [comment]
This is genearlly just considered "good hygiene" with installing signal handlers in libraries AFAIK, in the case that code isn't ready to handle `EINTR` this helps them "a bit", but not a huge amount. In theory though there should be no negative effects to this I think?

**Comment by Rufflewind** [comment]
I guess it depends a lot on what you use the signal handler for.  I want to use SIGINT+SIGTERM to interrupt whatever Rust is doing and exit the program gracefully (as opposed to just die without calling any destructors).  If it restarts, then if a part of the program is stuck on a blocking call, then I can't stop it gracefully and would have to SIGKILL.

**Comment by alexcrichton** [comment]
Hm well sure yeah makes sense but that's how this crate works at least? The tokio-signal support will wake up the event loop when a signal is received?

**Comment by Rufflewind** [comment]
If we assume that the loop contains only nonblocking calls, then it works fine, which I guess is reasonable to assume when you're using Tokio.  But in the edge case where there are blocking calls within the loop then they would instead auto-restart when a signal is received, which means it won't wake up the event loop until the blocking call finishes.  But I guess that's considered "abnormal use"?

**Comment by alexcrichton** [comment]
Yeah when you couple this with the fact that in a multithreaded application you don't actually know which thread the signal goes to, I'm not sure you can really reliably have a thread get unblocked on a signal.

**Comment by Rufflewind** [comment]
Okay, thanks I appreciate the clarification!
