### ISSUE TITLE
crtl_c doesn't work with powershell

### ISSUE THREAD

**Issue by Yanpas** [alexcrichton/tokio-signal#18]
Powershell kills process after first ctrl+c.

**Comment by alexcrichton** [comment]
Thanks for the report! Unfortunately signals are *way* different on Windows so I'm not really sure what's going on here. If a fix is found though I'd love to add it!

**Comment by Yanpas** [comment]
It seems VS Code runs powershell in some ugly way. Wasn't able to reproduce on pure psh session.
