### ISSUE TITLE
Support for Newer Tokio Releases

### ISSUE THREAD

**Issue by henninglive** [alexcrichton/tokio-signal#22]
I would like to use this crate with tokio `0.1.4^`, instead of having to handle signals myself. Is there interest in supporting the newer releases or are we waiting for the tokio and futures APIs to become more stable?

**Comment by alexcrichton** [comment]
Certainly! I was hoping to wait until the futures story settled down first, though, to make a breaking change and update to whatever the current state of tokio is by that point

**Comment by zonyitoo** [comment]
Hmm, I am migrating my project to `tokio` but get stuck on this crate. When will the "breaking change and update" start?

**Comment by alexcrichton** [comment]
I think this crate could probably in the 0.1 series grow support for the `tokio` crate without breaking backwards-compatibility (perhaps with some methods to be renamed on the next `futures` version), and I'd definitely be willing to review such a PR!

**Comment by zonyitoo** [comment]
I would prefer a breaking change ... It's hard to find another prefect names for those APIs. :(
One perfect solution is to find a way to convert the `Handle` from `tokio` to the one in `tokio_core`. Many existed `tokio-*` crates are based on `tokio_core`.

**Comment by alexcrichton** [comment]
Yes I believe that was part of the original design but I don't think it's come to fruition. In the meantime I'd personally prefer to pick slightly-worse names for now given to maintain backwards compatibility with tokio-core and futures 0.1, and we can break everything once the next stable version of futures is released (I don't believe 0.2 is that version)

**Comment by Marwes** [comment]
Also ended up blocked on this crate when doing the upgrade. I'd be interested in making a PR for the upgrade but I can't figure out how to spawn futures. `tokio_core` is able to this using `Handle` but `tokio` expects a thread local to be set for https://docs.rs/tokio-executor/0.1.2/tokio_executor/fn.spawn.html .

Is there some way to do this that I have missed? Making a breaking change to support tokio seems like the only to me

**Comment by alexcrichton** [comment]
Sorry I don't really have the time right now to invest into looking into issues here, if a breaking changes is necessary then it seems like it'll be necessary

**Comment by zonyitoo** [comment]
@Marwes I haven't started yet.
