### ISSUE TITLE
Can't use Signal::with_handle with a current_thread::Handle

### ISSUE THREAD

**Issue by coder543** [alexcrichton/tokio-signal#35]
Due to limitations of an external C library, I need to use a `CurrentThread` executor, but there doesn't seem to be a way to combine that with `tokio-signal`. `Signal::with_handle` is expecting a different `Handle` struct.

https://docs.rs/tokio/0.1.7/tokio/executor/current_thread/struct.CurrentThread.html#method.handle

Is there some way to work around this?

**Comment by Marwes** [comment]
The handle that `with_handle` requires is a handle to the reactor and not executor https://docs.rs/tokio-reactor/0.1.2/tokio_reactor/struct.Handle.html https://docs.rs/tokio-signal/0.2.1/tokio_signal/unix/struct.Signal.html#method.new . You should just be able to call `Signal::new` assuming you are currently executing inside an event loop (it does not matter that you are using `current_thread`).

**Comment by ipetkov** [comment]
Hey @coder543, I think Marwes' advice above should help, so I'm going to resolve this. Feel free to reopen if I've made a mistake!
