### ISSUE TITLE
Proposal for getting rid of the first loop must live limitation

### ISSUE THREAD

**Issue by vorner** [alexcrichton/tokio-signal#4]
Hello

While learning Rust I decided to write my own event loop. And kind of failed, I got really hairy interface. However, I managed to write signal handling with less limitations. It's not future/tokio aware, but I think I could try to port it into this codebase (I don't think creating another competing crate for tokio signal handling makes much sense).

The code is mostly here (a bit is in other files, but this is the relevant part):
https://github.com/vorner/eveboros/blob/master/src/signal_dispatch.rs

Should I try and create a pull request? What is your opinion on depending on the `nix` crate?

**Comment by alexcrichton** [comment]
Hm unfortunately your example runs a risk of deadlock. You can't acquire locks and such from a signal handler, so [this line](https://github.com/vorner/eveboros/blob/master/src/signal_dispatch.rs#L91) can cause a deadlock.

That being said I'd love to lift this restriction! It is indeed onerous to work around sometimes.

**Comment by vorner** [comment]
Actually, it does not (almost, there's a bug), but it's not entirely clear at the first glance. Because:

* Signal handlers are blocked from within themselves, so I can't get eg. `SIGCHLD` from a `SIGCHLD` handler itself (well, OK, I can get another signal from there, which needs to be solved, likely by a separate mutex for each signal).
* The only other place that locks the mutex is https://github.com/vorner/eveboros/blob/master/src/signal_dispatch.rs#L102, but few lines before I mask all the signals temporarily, so I don't get the signal handler from within the same thread at that time. Signal on another thread doesn't hurt, the signal handler can wait that little while (we could maybe use a spinlock implemented in userspace with atomic bool, so we are 100% sure there's no problem with putting the blocked thread to sleep by kernel).

But you're right this is a delicate thing. There are some more things that could be done:
 * Finding a lock-less data structure (I haven't looked if they already exist on crates.io)
 * Having a separate thread that'd just broadcast the signals and do the locking, the signal handler would only write into a single channel. But a separate thread is a bit ugly.
 * At least have a stress test that has a high chance triggering any possible deadlock if one is present.

**Comment by alexcrichton** [comment]
Oh oops I did indeed miss that! Sorry about that.

I think, though, that there may still be problems. The set of functions that can run in a signal handler are quite small, and I think for example that memory allocation isn't one of them. It looks, though, like you're [allocating in a signal handler](https://github.com/vorner/eveboros/blob/bd87cbbdb05b5f6b0375537b5096a31ebd90c950/src/signal_dispatch.rs#L80)? 

It's true that work could be offloaded to another thread, and that's basically what happens right now, where "thread" is just "task on a reactor"

**Comment by vorner** [comment]
Hmm, I'm quite new in Rust, I missed that it's allocating (I was thinking in terms of dropping the elements that no longer work… and because I missed `Vec.retain_mut`, I worked around it this way). This turns out to be a more interesting challenge that expected at first. Alright, I'll try to find some time to propose some real code, hopefully soon.

Thinking about it, I have no idea if using the channel is actually safe in a signal handler.

**Comment by alexcrichton** [comment]
Yeah that's what I'd be worried about :(.

Like with libc, most of libstd would need to be avoided in signal handlers.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/tokio-signal/pull/6
