### ISSUE TITLE
Promote to a first class Tokio component?

### ISSUE THREAD

**Issue by carllerche** [alexcrichton/tokio-signal#49]
I think `tokio-signal` is pretty fundamental and would like to see it become a first class Tokio component.

@ipetkov, it looks like you are maintaining this now. Would you be interested in moving this into the Tokio git repository? I can add you as a maintainer there. The first step would be to open a PR that moves the code over.

The main advantage would be that `tokio-signal` would be maintained in lock step with the rest of Tokio (wouldn't lag) and we could use it in official docs.

**Comment by ipetkov** [comment]
Sure, sounds like a great idea! I'll try to open a PR for this later this week before I go on vacation (if not I'll work on this after)

cc @alexcrichton and @Marwes in case they have any opinions on this

**Comment by vorner** [comment]
Just a technical one. It would be great not to just copy the sources over, but do something that preserves history (`git merge --allow-unrelated-histories` after preparing the smaller repo to live in subdirectory).

**Comment by carllerche** [comment]
@vorner the history could be preserved by referencing this repository (archived at that point). I don't think this should be deleted as there is history in issue discussion and PRs too.

What do you see value wise in bringing in the history as well as opposed to referencing here?

**Comment by carllerche** [comment]
I'm not necessarily opposed. This strategy just hasn't been used when importing other components.

The commit / merge style is different and I would expect that all the issue / PR references in commit messages would end up pointing to the wrong issues. Like, a merge commit that references `tokio-signal#50` would then link to `tokio#50`.

Thoughts?

**Comment by ipetkov** [comment]
Yeah that’s definitely a downside. For a small crate like this maybe it’s not worth the effort to try rewriting the history to change every #... into old/tokio-signal/#...

**Comment by vorner** [comment]
I'd understand if you didn't want to go with the rewriting, but it's not that hard ‒ basically, this command should do the trick.

```
git filter-branch -f --msg-filter 'sed -e "s/#\([0-9][0-9]*\)/old\/tokio-signal#\1/"' master
```

I mean, it's not a big pain but it's a bit annoying if I want to understand something, try to look the whole commit that introduce a line and read its commit message and find something like „Import tokio-signal into tokio“ with a reference to the older repository.

If you like, I can prepare the merge request.

**Comment by ipetkov** [comment]
> If you like, I can prepare the merge request.

Will be out for the next few weeks, so feel free!

**Comment by carllerche** [comment]
@ipetkov could you add me as a crate owner before you leave?

**Comment by ipetkov** [comment]
@carllerche done!

**Comment by ipetkov** [comment]
The code has been merged into the tokio repo, I've updated the README with a warning and a link to the new repo.

@alexcrichton could you resolve this issue, and then archive the repo for posterity?

**Comment by alexcrichton** [comment]
Sure thing
